### PR TITLE
dev 1.3.1 - crc filecheck

### PR DESCRIPTION
**Pull request by mteiting**
- added CRC32.cs
- Changed TabHelper.cs (edited public void CheckTabDirtyState())
- Added request if file has been deleted/changed
- Added CheckTabDirtyState to ChangedIndex event.
- Changed Class FileInfo for CRC check

(changes on the other .cs files done by "Codemaid" automatically, just formatting - removing whitespaces etc)

### CODE REVIEW

**Comment by nevadascout** [comment]
Looks like StyleCop and CodeMaid are going to be fighting over the formatting for this... :P

BTW - why was this closed? (I can't accept the pull request unless it's open)

**Comment by mteiting** [comment]
Actually I wanted to merge it with my own branch, but github selected yours automatically, and I didn't realize that, so I closed it.

But if you have a use for my code, feel free to use it... if your StyleCop let's my CodeMaid win :P.

btw - is there any update yet? - it's been a while since last update.

**Comment by nevadascout** [comment]
Ahhh, I see.

Yeah, I'm more than happy to use it - thanks!

There hasn't been yet - I've been pretty busy at work so haven't had much time to spend on Dash lately :(

**Comment by mteiting** [comment]
http://steamcommunity.com/profiles/76561197993255139
If you need support/help you can add me on steam.

**Comment by nevadascout** [comment]
I've added you on Steam :)

**Comment by nevadascout** [comment]
(Leaving this open so I don't forget about it)

**Comment by trdwll** [comment]
I've already updated it in the 1.3. I'll push later.

(Which is why I closed it lol)

**Pull request closed without merging**
